services:
  app:
    image: one-among-us-about-site
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./content:/usr/src/app/content
      - ./package.json:/usr/src/app/package.json
      - ./uno.config.ts:/usr/src/app/uno.config.ts
    ports:
      - 5173:5173
    container_name: one-among-us-about-site